import aldo from './body/logos/aldo.svg';
import aldo_acc from './body/logos/aldoacc.svg';
import aero from './body/logos/aero.svg';
import birken from './body/logos/birken.svg';
import crocs from './body/logos/crocs.svg';
import dune from './body/logos/dune.svg';
import inglot from './body/logos/inglot.svg';
import lc from './body/logos/lc.svg';
import levis from './body/logos/levis.svg';
import lav from './body/logos/lav.svg';
import nat from './body/logos/nat.svg';
import rb from './body/logos/rb.svg';
import nine from './body/logos/nine.svg';
import spring from './body/logos/callitspring.svg';
import beverly from './body/logos/beverly.svg';
import ardene from './body/logos/ardene.svg';
import rituals from './body/logos/rituals.svg';
import newyorker from './body/logos/newyorker.svg';
import havaianas from './body/logos/havaianas.svg';
import herschel from './body/logos/herschel.svg';
import hush from './body/logos/hush.svg';
import tcp from './body/logos/tcp.svg';
import toms from './body/logos/toms.svg';
import xside from './body/logos/xside.svg';
import lc_dreams from './body/logos/lc_dreams.svg';

export const data_list = [
  {
    id: 1,
    brand: 'Aeropostale',
    logo: aero,
    offer1: 'Flat 50% Off',
    offer2: 'On Everything',
    stores: ['DEIRA CITY CENTRE',
      'AL GHURAIR CENTRE',
      'IBN BATTUTA MALL',
      'MIRDIF CITY CENTRE',
      'BURJUMAN CENTRE',
      'DUBAI HILLS MALL',
      ],
  },
  {
    id: 2,
    brand: 'Aldo',
    logo: aldo,
    offer1: 'Flat 40% Off',
    offer2: 'On Selected Items',
    stores: [
      'ARABIAN CENTRE',
'DEIRA CITY CENTRE',
'MIRDIF CITY CENTRE',
'IBN BATTUTA MALL',
'DUBAI FESTIVAL CITY',
'DUBAI MARINA MALL',
'SPRING VILLAGE',
'MERCATO CENTRE',
'MALL OF THE EMIRATES',
'AL GHURAIR CENTRE',
'BURJUMAN CENTRE',
'DUBAI MALL',
    ],
  },
  {
    id: 3,
    brand: 'Aldo Acc',
    offer1: 'Flat 40% Off',
    offer2: 'On Selected Items',
    logo: aldo_acc,
    stores: ['MIRDIF CITY CENTRE',
      'MY CITY CENTRE',
     'DUBAI FESTIVAL CITY',
     'DUBAI MALL',
     'DEIRA CITY CENTRE',
      'MERCATO CENTRE',
      'MALL OF THE EMIRATES',
      'AL GHURAIR CENTRE',
      'BURJUMAN CENTRE',
      'DUBAI MALL',
      ],
  },
  {
    id: 4,
    brand: 'Ardene',
    logo: ardene,
    offer1: 'Flat 50% Off',
    offer2: 'On Everything',
    stores: ['BURJUMAN CENTRE',
    'DUBAI HILLS MALL',
    ],
  },
  {
    id: 5,
    brand: 'Beverly Hills & Polo Club',
    logo: beverly,
    offer1: 'Flat 40%',
    offer2: 'On Everything',
    stores: ['IBN BATTUTA MALL',
    'DUBAI FESTIVAL CITY',
    'AL GHURAIR CENTRE',
    'BURJUMAN CENTRE',
    'DEIRA CITY CENTRE',
    'DUBAI MALL',
    'MALL OF THE EMIRATES',
    'NAKHEEL MALL',
    'DUBAI HILLS MALL',
    ],
  },
  {
    id: 6,
    brand: 'Birkenstock',
    logo: birken,
    offer1: '25% To 50%',
    offer2: 'On Selected Styles',
    stores: ['MALL OF THE EMIRATES',
    'Mirdif City Centre',
    'IBN BATTUTA MALL',
    'DUBAI MARINA MALL',
    'DEIRA CITY CENTRE',
    'BURJUMAN CENTRE',
    'NAKHEEL MALL',
    'DUBAI HILLS MALL',
    ],
  },
  {
    id: 7,
    brand: 'Call it Spring',
    logo: spring,
    offer1: 'Flat 40% Off',
    offer2: 'On Everything',
    stores: ['MALL OF THE EMIRATES',
      'DUBAI FESTIVAL CITY',
      'DEIRA CITY CENTRE',
      'MIRDIF CITY CENTRE',
      'BURJUMAN CENTRE',
      ],
  },
  {
    id: 8,
    brand: 'CROCS',
    logo: crocs,
    offer1: '25% To 50%',
    offer2: 'On Selected Styles',
    stores: [
      'AL GHURAIR CENTRE',
'DUBAI MALL',
'MALL OF THE EMIRATES',
'BURJUMAN CENTRE',
'DEIRA CITY CENTRE',
'DUBAI FESTIVAL CITY',
'IBN BATTUTA MALL',
'ARABIAN CENTRE',
'DUBAI HILLS MALL' ],
  },
  {
    id: 9,
    brand: 'Dune London',
    logo: dune,
    offer1: 'Flat 40% Off',
    offer2: 'On Selected Items',
    stores: [
      'DUBAI MARINA MALL',
' Mirdif City Centre',
'MALL OF THE EMIRATES',
'DUBAI MALL (GF)',
'AL GHURAIR CENTRE',
'BURJUMAN CENTRE',
    ],
  },
  {
    id: 10,
    brand: 'Havaianas',
    logo: havaianas,
    offer1: 'Flat 30% Off',
    offer2: 'On Everything',
    stores: ['DUBAI HILLS MALL'],
  },
  {
    id: 11,
    brand: 'Herschel',
    logo: herschel,
    offer1: 'Flat 40% Off',
    offer2: 'On Everything',
    stores: ['BURJUMAN CENTRE'],
  },
  {
    id: 12,
    brand: 'Hush Pupies',
    logo: hush,
    offer1: 'Flat 50% Off',
    offer2: 'On Selected Items',
    stores: [
      'BURJUMAN CENTRE'
    ],
  },
  {
    id: 13,
    brand: 'Inglot',
    logo: inglot,
    offer1: 'Bundle Offers',
    offer2: '',
    stores: [
      'MALL OF THE EMIRATES',
      'BURJUMAN CENTRE',
      'DUBAI HILLS MALL'
    ],
  },
  {
    id: 14,
    brand: 'La vie n rose',
    logo: lav,
    offer1: 'Flat 50% Off',
    offer2: 'On Selected Items',
    stores: ['BURJUMAN CENTRE',
    'IBN BATTUTA MALL',
    'MALL OF THE EMIRATES',
    'DUBAI HILLS MALL',
    ],
  },
  {
    id: 15,
    brand: 'LC Waikiki',
    logo: lc,
    offer1: 'Flat 30% Off',
    offer2: 'On Everything',
    stores: ['IBN BATTUTA MALL',
    'DEIRA CITY CENTRE',
    'BURJUMAN CENTRE',
    'MIRDIF CITY CENTRE',
    'DUBAI MALL',
    'AL GHURAIR CENTRE',
    'DUBAI HILLS MALL',
    ],
  },
  {
    id: 150,
    brand: 'LC Dreams',
    logo: lc_dreams,
    offer1: 'Flat 30% Off',
    offer2: 'On Everything',
    stores: ['DUBAI HILLS MALL',
    ],
  },
  {
    id: 16,
    brand: 'Levis',
    logo: levis,
    offer1: 'Flat 40% Off',
    offer2: 'On Selected Items',
    stores: ['DUBAI FESTIVAL CITY',
    'MIRDIF CITY CENTRE',
    'DEIRA CITY CENTRE',
    'BURJUMAN CENTRE',
    'IBN BATTUTA MALL',
    ],
  },
  {
    id: 17,
    brand: 'Levis',
    logo: levis,
    offer1: 'Flat 25% Off',
    offer2: 'On Everything',
    stores: [
    'MALL OF THE EMIRATES',
    'DUBAI MALL',
    'DUBAI HILLS MALL',
    ],
  },
  {
    id: 18,
    brand: 'NATURALISER',
    logo: nat,
    offer1: 'Flat 40% Off',
    offer2: 'On Selected Items',
    offer3: 'Buy 2 More Get Extra 20% Off',
    stores: ['MIRDIF CITY CENTRE',
      'MALL OF THE EMIRATES',
      'BURJUMAN CENTRE',
      'DUBAI FESTIVAL CITY',
      'ARABIAN CENTRE',
      ],
  },
  {
    id: 19,
    brand: 'New Yorker',
    logo: newyorker,
    offer1: 'Flat 25% Off',
    offer2: 'On Everything',
    stores: ['IBN BATTUTA MALL',
    'DUBAI FESTIVAL CITY'],
  },
  {
    id: 20,
    brand: 'NINE WEST',
    logo: nine,
    offer1: 'Flat 40% Off',
    offer2: 'On Selected Items',
    stores: ['AL GHURAIR CENTRE',
    'DEIRA CITY CENTRE',
    'MALL OF THE EMIRATES',
    'DUBAI FESTIVAL CITY',
    'ARABIAN CENTRE',
    'DUBAI MALL',
    'MIRDIF CITY CENTRE',
    'DUBAI HILLS MALL MALL',
    ],
  },
  {
    id: 21,
    brand: 'R&B',
    logo: rb,
    offer1: 'Flat 30% Off',
    offer2: 'On Everything',
    stores: ['AL GHURAIR CENTRE',
    'DEIRA CITY CENTRE',
    'IBN BATTUTA MALL',
    'DUBAI HILLS MALL'],
  },
  {
    id: 22,
    brand: 'Rituals',
    logo: rituals,
    offer1: 'Flat 25% Off',
    offer2: 'On Selected Items',
    stores: ['IBN BATTUTA MALL',
    'MIRDIF CITY CENTRE',
    'ARABIAN CENTRE',
    'MALL OF THE EMIRATES',
    'BURJUMAN CENTRE',
    'DUBAI MARINA MALL',
    'DUBAI OUTLET MALL',
    'DUBAI MALL',
    'DUBAI HILLS MALL',
    ],
  },
  {
    id: 23,
    brand: 'TCP',
    logo: tcp,
    offer1: 'Flat 50% Off',
    offer2: 'On Selected Items',
    stores: ['DUBAI MALL',
    'IBN BATTUTA MALL',
    'DEIRA CITY CENTRE',
    'MIRDIF CITY CENTRE',
    'DUBAI HILLS MALL',
    'AL GHURAIR CENTRE',
    ],
  },
  {
    id: 24,
    brand: 'TOMS',
    logo: toms,
    offer1: 'Flat 40% Off',
    offer2: 'On Selected Items',
    stores: ['DEIRA CITY CENTRE',
    'MALL OF THE EMIRATES',
    'DUBAI MALL',
    'MIRDIF CITY CENTRE',
    'DUBAI HILLS MALL',
    ],
  },
  {
    id: 25,
    brand: 'Xside',
    logo: xside,
    offer1: 'Flat 30% Off',
    offer2: 'On Everything',
    stores: ['DUBAI HILLS MALL',
    ],
  },

];
